### ISSUE TITLE
Support http schema?

### ISSUE THREAD

**Issue by bailantaotao** [fsouza/fake-gcs-server#103]
HI there,

I have started a fake-gcs-server docker container to do unit test.
Then i'm meet some problems about wrong reader host (It should indicate fake-gcs-server, like `127.0.0.1:4443`).

I don't want to modify my `/etc/hosts`, so i try to set env `$STORAGE_EMULATOR_HOST` in my unit test. The schema will assign to `http` [[LINK](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L117)] in GCS library when i set the `STORAGE_EMULATOR_HOST` env. But fake-gcs-server schema is https...XD

So would you like to add a flag to indicate schema is for https or http? 
or do you have other suggestion?

**Comment by fsouza** [comment]
Hey @bailantaotao, we can probably introduce an option for that, but may I ask why you're starting this in a container instead of using it as a library for unit tests?

**Comment by bailantaotao** [comment]
Sorry reply too late,

I have use library as my top option in unit test, thanks!
It's seems to me that this issue can be closed.

**Comment by cuonglm** [comment]
@fsouza What need to change to make it support HTTP?

I try using HTTP transport, change `StartTLS` -> `Start`, then I always get:

```
--- FAIL: TestServerClientBucketAttrs (0.00s)
    --- FAIL: TestServerClientBucketAttrs/tcp_listener (0.00s)
        bucket_test.go:30: Get https://storage.googleapis.com/storage/v1/b/some-bucket?alt=json&prettyPrint=false&projection=full: http: server gave HTTP response to HTTPS client
--- FAIL: TestServerClientBucketAttrsAfterCreateBucket (0.00s)
    --- FAIL: TestServerClientBucketAttrsAfterCreateBucket/tcp_listener (0.00s)
        bucket_test.go:54: Get https://storage.googleapis.com/storage/v1/b/best-bucket-ever?alt=json&prettyPrint=false&projection=full: http: server gave HTTP response to HTTPS client
    --- FAIL: TestServerClientBucketAttrsAfterCreateBucket/tcp_listener#01 (0.00s)
        bucket_test.go:54: Get https://storage.googleapis.com/storage/v1/b/best-bucket-ever?alt=json&prettyPrint=false&projection=full: http: server gave HTTP response to HTTPS client
--- FAIL: TestServerClientBucketAttrsAfterCreateBucketByPost (0.00s)
    --- FAIL: TestServerClientBucketAttrsAfterCreateBucketByPost/tcp_listener (0.00s)
        bucket_test.go:78: Post https://storage.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=whatever: http: server gave HTTP response to HTTPS client
    --- FAIL: TestServerClientBucketAttrsAfterCreateBucketByPost/tcp_listener#01 (0.00s)
        bucket_test.go:78: Post https://storage.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=whatever: http: server gave HTTP response to HTTPS client
```

I try setting `STORAGE_EMULATOR_HOST` to force `HTTP` but no luck, any suggestion?

**Comment by cuonglm** [comment]
I add HTTP support in https://github.com/fsouza/fake-gcs-server/pull/154
