### ISSUE TITLE
Cannot use signed url with java

### ISSUE THREAD

**Issue by marcelocamanho** [fsouza/fake-gcs-server#1073]
Was anyone able to use them?
I am using a simple code to init the storage service and to access it, but it fails.

```
StorageOptions.Builder storageOptions = StorageOptions.newBuilder().setProjectId(projectId);
storageOptions.setHost("http://localhost:1234");
BlobInfo blobInfo = BlobInfo.newBuilder(BlobId.of(bucketName, objectName)).build();
URL url = storage.signUrl(blobInfo, 10, TimeUnit.MINUTES, Storage.SignUrlOption.withV4Signature());

```

This causes the error:
```
java.lang.IllegalStateException: Signing key was not provided and could not be derived
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[guava-20.0.jar:na]
	at com.google.cloud.storage.StorageImpl.signUrl(StorageImpl.java:627) ~[google-cloud-storage-2.8.1.jar:2.8.1]

```

Was anyone able to work around this please? 

Thanks

**Comment by fsouza** [comment]
Hey @marcelocamanho, sorry for such a delayed response, I completely missed this issue. Signing URLs doesn't really involve the server, so you need a valid key to sign even if you're using a fake server. What I've seen other folks do in the past is generating some sort of X.509 certificate or even generating a real one from Google, invalidating it and then using in tests/CI.

**Comment by SamueLacmene** [comment]
@marcelocamanho Did you find a solution to your Problem? I'm facing the same issue

**Comment by SamueLacmene** [comment]
I managed to mock the credential, so that the method `storage.signUrl` was able to work without having to use a -`service-account-key.json`. Here is the solution:

```
@Configuration
class GoogleCloudStorageConfiguration {

  @Value("\${gcs.port}")
  private lateinit var gcsContainerPort: String

  @Bean
  @Primary
  fun storage(): Storage {
    val serviceAccountCredentials = mock<ServiceAccountCredentials> {
      on { account } doReturn "Account"
      on { sign(any()) } doReturn byteArrayOf(123456.toByte())
    }

    return StorageOptions.getUnauthenticatedInstance().toBuilder()
      .setHost("http://localhost:$gcsContainerPort")
      .setCredentials(serviceAccountCredentials)
      .build()
      .service
  }
}
```

I'm using Sprint + kotlin + mockito

```
import org.mockito.kotlin.any
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.mock
```

**Comment by Burtan** [comment]
While the fake signing is working for me. The generated url does not use the fake gcs url, but https://storage.googleapis.com/.

**Comment by tlusk** [comment]
Here's a way you can create a new `ServiceAccountCredentials` object without needing to mock it like the above solution:

```kotlin
val storage = StorageOptions.newBuilder()
  .setCredentials(
      ServiceAccountCredentials.newBuilder().apply {
          clientEmail = "TestAccount"
          privateKey = KeyPairGenerator.getInstance("RSA").generateKeyPair().private
      }.build(),
  )
  .build().service
```
