### ISSUE TITLE
createWriteStream() with resumable true results in absolute URLs error on 1.45.1

### ISSUE THREAD

**Issue by byumark** [fsouza/fake-gcs-server#1170]
We recently upgraded to fake-gcs-server 1.45.1 and started getting the following error from google-cloud/storage when streaming to the fake gcs server using `createWriteStream()`:

```TypeError: Only absolute URLs are supported```

When we move back to 1.45.0, then we no longer have the issue. Also, if we set `resumable` to `false` then 1.45.1 does not cause an error. For example:

```createWriteStream({ resumable: false })```

**Comment by fsouza** [comment]
Thanks for reporting and apologies for the breakage. This is the same issue as #1166 (different SDKs have different error messages).

I broke it in #1159. #1184 fixes it.
