### ISSUE TITLE
Breaking change (port) in latest version (1.47.0)

### ISSUE THREAD

**Issue by Strernd** [fsouza/fake-gcs-server#1273]
According to the doc changes in the latest release:

> `-scheme` can be used to specify the protocol.  
The binding port will be `-port` (defaults to `4443`).  
For example, the previous example could be changed to pass `-scheme http`:

and

> To start both HTTPS and HTTP servers, pass `-scheme both`.  
HTTPS will bind to `-port` (defaults to `4443`) and HTTP will bind to `-port-http` (defaults to `8000`).  
For example, the previous example could be changed to pass `-scheme both`:

I would expect if I used the following command `fake-gcs-server -scheme http` that the port would be `4443` as in the last version. Since this release it changed to another port and it broke our CI.

`fake-gcs-server -scheme http -port 4443` restores the old behaviour.

**Comment by fsouza** [comment]
Fixed via #1272. Thanks for reporting!
