### ISSUE TITLE
etag value has extra backslashes when uploading object

### ISSUE THREAD

**Issue by szgupta** [fsouza/fake-gcs-server#1327]
When uploading an object against a `fake-gcs-server`, I'm noticing that the `etag` value has escaped backslashes before and after the actual md5 hash. Looks to be due to poor escaping. A GCS client library that I'm using fails to parse the `etag` attribute because of this. I wasn't able to repro when uploading against GCS itself.

Raw json output when uploading against `fake-gcs-server`:
```
"... , \"etag\": \"\\\"1B2M2Y8AsgTpgAmY7PhCfg==\\\"\", ..."
```

Raw json output when uploading against GCS itself:
```
"... , \"etag\": \"TKb9iteyqIEDEEE=\", ..."
```

**Comment by fsouza** [comment]
@szgupta can you provide more details a bit? Like which backend are you using (if you can share the command you used to start the server, that would be perfect) and a small reproducer with the client you're using. I suspect the issue is not specific to any clients or the backend, but having more information helps me debug the issue.

Also, is that JSON snippet from the response for get object?

**Comment by seemeroland** [comment]
Here is a minimal reproduction:

Start with some test data.
```
mkdir data
cd data
mkdir test-bucket
cd test-bucket
echo "text" > text.txt
```

Go back to base directory and start fake-gcs-server through docker
```
docker run -d --name fake-gcs-server -p 4443:4443 -v ./data:/data fsouza/fake-gcs-server -scheme http
```

Get objects with prefix
```
curl http://localhost:4443/storage/v1/b/test-bucket/o?prefix=te
```

Output:
```
{"kind":"storage#objects","items":[{"kind":"storage#object","name":"text.txt","id":"test-bucket/text.txt","bucket":"test-bucket","size":"5","contentType":"text/plain; charset=utf-8","crc32c":"KOsDaQ==","acl":[{"bucket":"test-bucket","entity":"projectOwner-test-project","object":"text.txt","projectTeam":{},"role":"OWNER"}],"md5Hash":"4cuww4ea+DRyRvEsVZqGtQ==","etag":"\"4cuww4ea+DRyRvEsVZqGtQ==\"","timeCreated":"2023-11-10T00:35:12.25986Z","updated":"2023-11-10T00:35:12.25989Z","generation":"1699576512259897"}]}
```
etag is `"etag":"\"4cuww4ea+DRyRvEsVZqGtQ==\""`
