### ISSUE TITLE
Cannot set ACL on ObjectHandle

### ISSUE THREAD

**Issue by henrahmagix** [fsouza/fake-gcs-server#137]
With latest v1.14.1:
```go
err = obj.ACL().Set(gs.ctx, storage.AllUsers, storage.RoleReader)
// err.Error() == "json: cannot unmarshal string into Go struct field Object.acl of type []*storage.ObjectAccessControl"
```

This code is very similar to an example taken from the `cloud.google.com/go/storage` docs, so I feel like it should be supported: https://godoc.org/cloud.google.com/go/storage#ACLHandle.Set

**Comment by fsouza** [comment]
Looks like this is fixed in #125. Feel free to reopen otherwise.
