### ISSUE TITLE
[BUG] Range Reader returning wrong bytes

### ISSUE THREAD

**Issue by ls-tommy-baloukas** [fsouza/fake-gcs-server#159]
I am currently using the fakestorage package in my project to unit test my GCS code. It seems like calling NewRangeReader(ctx, offset, length) returns the wrong bytes depending on what I pass in as offset and length. For example, say I have a GCS Object that contains the following text: "Hello There!" and my goal is to read this file in chunks until the entire file is read, I would get get the following => "Hlotee" if I chunk the reads by 2 bytes starting from 0 to EOF. 

I tested my code with a real GCS instance, and I get the correct data back after reading in chunks (2 byte size), so this seems to be related to the fakestorage package.

**Comment by fsouza** [comment]
Hi @ls-tommy-baloukas, thanks for reporting and apologies for the delayed response. Let's fix this :)

Can you share a reproducer so we can use it as a test to prevent regressions?

**Comment by fsouza** [comment]
Closing as stale.
