### ISSUE TITLE
1.49.1 gives me "Invalid Date" error in ruby google cloud storage implementation

### ISSUE THREAD

**Issue by AlvesJorge** [fsouza/fake-gcs-server#1632]
Sorry don't have the time to provide a working reproducible example.

I tested 1.48, and 1.49.0 and I can confirm this only happens in 1.49.1

My implementation is a simple set client -> set bucket > `bucket.upload(bytes, path)`, and somehow I get an error saying "Invalid Date", where clearly I'm not setting anything date related in my upload arguments.

**Comment by AlvesJorge** [comment]
[Might be this change ](https://github.com/fsouza/fake-gcs-server/pull/1619/files#r1632356947)

**Comment by fsouza** [comment]
Thanks for reporting and sorry for the breakage. I just published 1.49.2. Can you confirm that this issue is fixed in that release?

**Comment by AlvesJorge** [comment]
Yes, it is indeed working normally! 
No worries with the bug, this project is very useful and I'm very grateful for it, keep up the great work! 😄
