### ISSUE TITLE
Error - Download file

### ISSUE THREAD

**Issue by WillRy** [fsouza/fake-gcs-server#196]
Hello everyone,

Sorry to bother opening an issue, but I have a question about the implementation, because I'm having an error when trying to download a file.

When downloading the file with the code:

```golang

func (video *Video) Download(bucketName string, storagePath string) (Video, error) {
	ctx := context.TODO()

	//client, err := storage.NewClient(ctx)
	transCfg := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // ignore expired SSL certificates
	}
	httpClient := &http.Client{Transport: transCfg}

	client, err := storage.NewClient(ctx, option.WithEndpoint("https://fake:4443/storage/v1/"), option.WithHTTPClient(httpClient))


	if err != nil {
		video.Status = "error"
		fmt.Println(err.Error())
		return *video, err
	}


	bkt := client.Bucket(bucketName)

	obj := bkt.Object(video.Path)

	r, err := obj.NewReader(ctx)

	if err != nil {
		video.Status = "error"
		fmt.Println(err.Error())
		return *video, err
	}

	defer r.Close()

	body, err := ioutil.ReadAll(r)
	if err != nil {
		video.Status = "error"
		fmt.Println(err.Error())
		return *video, err
	}

	f, err := os.Create(storagePath+"/"+video.Uuid+".mp4");

	if err != nil {
		video.Status = "error"
		fmt.Println(err.Error())
		return *video, err
	}

	_, err = f.Write(body)

	if err != nil {
		video.Status = "error"
		fmt.Println(err.Error())
		return *video, err
	}

	defer f.Close()

	fmt.Println("Video ", video.Uuid, "has been stored")

	return *video, nil
}

```

The error comes from: **newReader**

**Error:**
storage: object doesn't exist

If I access the file via URL, I can do it normally.

The repository for my application is this:
https://github.com/WillRy/golang-gcs-test

obs. I have files pre-loaded through volumes, in docker-compose.yaml

Did I make a mistake?

Thank you very much in advance.

**Comment by fsouza** [comment]
Hey there, thanks for opening the issue and providing a reproducer! You need to set the public-host and use that in your client.

I've updated the Go example to show how to do that: https://github.com/fsouza/fake-gcs-server/commit/4ad5c60b79c955cebf0017a546e61672c23a7a26.

**Comment by WillRy** [comment]
This tool is extremely useful, thanks for the help
