### ISSUE TITLE
fake-gcs-server eats all memory

### ISSUE THREAD

**Issue by pitrou** [fsouza/fake-gcs-server#213]
I've downloaded the v1.18.1 binaries version for Linux and launched the server like this:
```
$ fake-gcs-server -filesystem-root /home/antoine/t -scheme http
```

Without even issuing a single request, fake-gcs-server started allocating a ton of memory and eating CPU, making my computer crawl:
```
  PID UTIL.     PR  NI    VIRT    RES    SHR S  %CPU %MEM    TEMPS+ COM.
31933 antoine   20   0 52,306g 0,044t      0 S  24,4 95,5   1:48.97 fake-gcs-server
```

I had to kill the process.

**Comment by pitrou** [comment]
Uh, looks like it's because it loads data from `/data` by default... and `/data` is a 300GB file tree on my computer :-/

**Comment by pitrou** [comment]
Closing as presumably not a bug...

**Comment by fsouza** [comment]
Hi @pitrou, thanks for opening this. Perhaps we can disable pre-loading from any dir unless explicitly requested?

Will reopen to track.

**Comment by pitrou** [comment]
Thanks for the quick response :-)

**Comment by nhoughto** [comment]
FYI This broke my build =) We were assuming not specified meant /data and were volume mounting into that path. I've fixed it now by specifying it :+1:
