### ISSUE TITLE
Checking if a folder exists is not working as expected

### ISSUE THREAD

**Issue by reaVen-** [fsouza/fake-gcs-server#215]
when connecting to googles endpoint by using
blob = storage.Blob(bucket=bucket, name="somefolder/")
fileExists = blob.exists() # true

however when overiding storage endpoints etc as explained in examples for python. and using the exact same code, fileExists is now false. It works as expected when checking for example 'name="somefolder/somefile.txt"'

**Comment by fsouza** [comment]
yeah I think it's a known limitation of the fs backend that "directory" objects aren't supported, unfortunately :( We could use some special folder at the root for metadata and storing this kind of info, but right now it isn't supported :(
