### ISSUE TITLE
Expected headers are not sent for ObjectHandle.NewReader()

### ISSUE THREAD

**Issue by ericnorris** [fsouza/fake-gcs-server#239]
The [Reader](https://godoc.org/cloud.google.com/go/storage#Reader) you get from `ObjectHandle.NewReader` has an `Attrs` field of type [ReaderObjectAttrs](https://godoc.org/cloud.google.com/go/storage#ReaderObjectAttrs).

The `storage` library fills those values in based on headers sent in the response: 

https://github.com/googleapis/google-cloud-go/blob/bd00477b309def1610fbf4cb259329deac795891/storage/reader.go#L255-L268

As far as I can tell, `fakestorage` is not setting these headers, which means that you get something like the following when you try to use them:

```
reader attrs: {Size:56 StartOffset:0 ContentType: ContentEncoding: CacheControl: LastModified:0001-01-01 00:00:00 +0000 UTC Generation:-1 Metageneration:0}
```

This library has been great, but including these headers would make it so that I can safely use the `Attrs` attribute _and_ be able to test. Thanks!

**Comment by fsouza** [comment]
Hi @ericnorris, thanks for reporting. Can you check if #240 fixes the issue for you?

Thanks!

**Comment by someone1** [comment]
I just conditionally added `Content-Encoding` - I don't think metadata generation is supported so I couldn't add that.

**Comment by ericnorris** [comment]
Hey @fsouza, I just had a chance to test locally and it does seem to fix the issue. Thanks, and thanks @someone1 for the quick fix!
