### ISSUE TITLE
Github Action?

### ISSUE THREAD

**Issue by ex-nerd** [fsouza/fake-gcs-server#256]
Are there plans to publish a version of this to the github actions marketplace?  I can whip up a version of this but it would probably make more sense for you to own the action's repository.

**Comment by fsouza** [comment]
Hey @ex-nerd, thanks for opening this issue. I'm not sure what you mean though. Do you mean running fake-gcs-server as a service in a job? If so, you should be able to use the Docker image for that.

If not, what would the action do? fake-gcs-server is a long-running process, so it can't be used as a regular step (afaik steps are always sequential?).

**Comment by ex-nerd** [comment]
@fsouza It would allow running of fake-gcs-server as a "service" within a github action.  You can see this one I set up for my employer for arangodb: https://github.com/xinova/arangodb-action

yes, it uses the docker image, but you still need provide github with a bit of information about the config. In the case of fake-gcs-server that would presumably mean some overrides for port number, "public" server name, etc.

**Comment by ex-nerd** [comment]
Here's the official documentation: https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action

Anyway, if you're interested, feel free to create an empty repo and I can submit a PR with some contents.  Then you'll have to log into the github action marketplace and register it.

**Comment by fsouza** [comment]
Ohh I see you use Docker to start a dettached container, that's very interesting 😁  Yeah will keep this issue open for tracking the idea, but I don't think I'd be able to tackle this issue anytime soon, unfortunately :(

(I thought you originally meant a service like documented here: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices, sorry about that 🙈)

**Comment by ex-nerd** [comment]
@fsouza Like I said, I'm happy to contribute a PR if you want to host the repo.  I eventually need to get this hooked up for work, anyway.

**Comment by fsouza** [comment]
Hey @ex-nerd, finally got to this. Can you take a look at https://github.com/fsouza/fake-gcs-action/pull/1? Does that make sense?

I haven't tested it yet, but I assume it would work? x)

**Comment by ex-nerd** [comment]
Haven't forgotten about this ... just got stuck in the backlog of work stuff.

**Comment by ex-nerd** [comment]
Just to confirm, this works great.  Thanks for setting this up.
