### ISSUE TITLE
One-too-many bytes returned when supplying a range header

### ISSUE THREAD

**Issue by gh2k** [fsouza/fake-gcs-server#263]
I think this was introduced by #255 (cc @chowey)

When calling fake-gcs from my tests, I am receiving one more byte than expected. This was working in version `1.18.4`.

For example, I have a range header that sets `bytes=0-8` and it receives 10 bytes back...
```JavaScript
        it('should be able to get back the first 9 bytes of the file', async function() {
          const options = {
            uri: fileUrl,
            headers: {
              Range: 'bytes=0-8'
            }
          }
          const res = await rp.get(options)
          expect(res.body).to.equal('hello wor')
        })
```
yields an error because the client receives `hello worl`.

**Comment by chowey** [comment]
Strange. Do you have more test code that I can see to reproduce this?

**Comment by fsouza** [comment]
Hey @gh2k, sorry for moving from bug to question, just trying to gather some info here: what is `rp.get` doing with the `Range` header? Is it forwarding it as is?

**Comment by gh2k** [comment]
Ah, sorry. I had clearly not had enough coffee when I posted that. That's a snippet of an acceptance test that talks to my wrapper, which had been erroneously incrementing `end` by 1, rather than the bit that talks to GCS. :man_facepalming: 

My implementation actually matched the buggy behaviour of `fake-gcs-server` and so the fix broke my tests. I'd assumed my app was doing the right thing, but I think it is indeed returning one too many bytes when given a range.
