### ISSUE TITLE
Do you have alpine distribution?

### ISSUE THREAD

**Issue by yiyue115** [fsouza/fake-gcs-server#301]

**Comment by fsouza** [comment]
Hi @yiyue115, thanks for opening the issue. Not sure what you mean, do you mean the Docker image? If so, it's already based on Alpine.

**Comment by yiyue115** [comment]
Hi Francisco, Thanks so much for the kind reply.. Sorry if this is a potential dumb question as I'm still quite new to docker. I can't seem to find it on https://pkgs.alpinelinux.org/packages 

Do you know any chance I could not pull it from the Docker public registry?

**Comment by fsouza** [comment]
Ohhh gotcha. Yeah I don't think there are any packages for alpine or any other distros currently :/ 

I personally don't know how to craft such packages and publish them, but I'll leave this issue open so we can track it.

**Comment by fsouza** [comment]
Closing because it's not our goal to track OS packaging here. I can help anyone who's interested in maintaining packages elsewhere though.
