### ISSUE TITLE
Generate Crc32c and Md5Hash when seeding from disk

### ISSUE THREAD

**Issue by fsouza** [fsouza/fake-gcs-server#313]
When loading objects from disk, we should also calculate the proper crc32 check and the md5 hash.

**Comment by antonydenyer** [comment]
This is a broader topic than just calculating hashes.

Currently when using a preloaded data from disk data is fetched at execution time. ie when you call the `ListBuckets` endpoint the function will read from disk at the point in time. Subsequent calls to `ListBuckets` will just read from disk again. You could have the scenario where folders/buckets are created without going through the `createBucket` endpoint. I don't think this is a problem.
