### ISSUE TITLE
can i use this on production, as GCS replacement 

### ISSUE THREAD

**Issue by batara666** [fsouza/fake-gcs-server#344]

**Comment by fsouza** [comment]
You certainly _can_, but definitely shouldn't. This is designed for tests and given its intent, I find it unlikely that I would take PRs improving fake-gcs-server as a real world replacement to GCS.

For production, you could in theory use some open source object store, such as minio or Swift, as long as you stick with the S3 API (iirc GCS has partial support for the S3 API).

**Comment by batara666** [comment]
i got 15TB on my storage, i may use it just 60% of total, is that okay ?
