### ISSUE TITLE
Setting blob.custom_time doesn't work, returns always None

### ISSUE THREAD

**Issue by oittaa** [fsouza/fake-gcs-server#410]
I have a piece of code like the following:
```
self.client = storage.Client()
self.bucket = self.client.get_bucket(bucket_name)

blob = self.bucket.blob(blob_name)
blob.upload_from_string(value, content_type=content_type)
blob.reload()
blob.custom_time = datetime.datetime.now(datetime.timezone.utc)
blob.patch()
```
If I set `custom_time` before uploading, even the real Google server erases it from the blob. That's why I patch it after the upload. The fake server unfortunately loses it even after `patch`.

```
blob = self.bucket.get_blob(blob_name)
print(blob.custom_time)
```
results in `None`

**Comment by oittaa** [comment]
To me it looks like the `Custom-Time` is completely missing from objects. https://github.com/fsouza/fake-gcs-server/blob/297b8cdcd2f8fac8652f8b20c023ececb1c368b1/fakestorage/object.go#L25-L43

https://cloud.google.com/storage/docs/metadata#custom-time
https://pkg.go.dev/cloud.google.com/go/storage#ObjectAttrsToUpdate

**Comment by oittaa** [comment]
The original Google Cloud issue about missing `custom_time` before patching is tracked here. https://github.com/googleapis/python-storage/issues/372

**Comment by fsouza** [comment]
Thanks for reporting and linking the docs!

**Comment by mar-pan** [comment]
Hello @fsouza is there any chance that this could be assigned to someone and resolved?

**Comment by fsouza** [comment]
I opened #1024 (big round-number!) as a draft, in case someone wants to work on it. It's unlikely I'll be able to pick it back up in the next couple of weeks.

**Comment by RachitSharma2001** [comment]
@fsouza I believe I have a solution that fixes this issue and updates `CustomTime` correctly. I am ready to submit a pr but since my solution is based off the changes I made to [this](https://github.com/fsouza/fake-gcs-server/pull/1016) PR (specifically the changes added to `PatchObject` method in `object.go`) I just want to make sure that those changes are good before submitting a pr to fix this issue.

**Comment by fsouza** [comment]
@RachitSharma2001 hey, I'm going to look at your PR later today (in 2 hours or so). If you prefer, you can open another PR on top of that one, or we can wait.

Apologies for the delayed review.
