### ISSUE TITLE
where do uploaded files go?

### ISSUE THREAD

**Issue by naseemkullah** [fsouza/fake-gcs-server#417]
Hello, thanks for this great tool!

My tests generally create data via uploads to buckets and then perform subsequent downloads of those files created in test.

However although the upload succeeds to the fake-gcs-server, i cannot subsequently download the file, is this expected behaviour or am I doing something wrong?

THanks!

**Comment by fsouza** [comment]
Hi @naseemkullah, can you share the code of what you're trying to do?

Files are stored either in memory or disk, but with either storage backend users should be able to retrieve objects after uploading them

**Comment by naseemkullah** [comment]
Good to know that uploaded files should be retrievable in either the memory or filesystem backends!

Stay tuned for a code snippet! Thanks.

**Comment by fsouza** [comment]
Closing as this was a question. Please feel free to reopen or open new issues in the future if other questions or issues come up!

**Comment by naseemkullah** [comment]
Ok thanks!
