### ISSUE TITLE
Response comply with API for object insert

### ISSUE THREAD

**Issue by tarsisazevedo** [fsouza/fake-gcs-server#420]
I am using java's gcs client and it expects some data from the response that fake-gcs-server dont provide. I think api should send a response with data expected, like described in this document https://cloud.google.com/storage/docs/json_api/v1/objects#resource

If you are ok with that, I can send a PR to fix this issue.

**Comment by fsouza** [comment]
Go for it. I assume we have all the data? Let me know if you run into any issues.

**Comment by fsouza** [comment]
This was fixed in #843.
