### ISSUE TITLE
Correct way to call multi-part request

### ISSUE THREAD

**Issue by nhatmvo** [fsouza/fake-gcs-server#422]
I use postman to test the gcs and this is my curl: 
`curl --location --request POST 'https://localhost:4443/upload/storage/v1/b/sample-bucket/o?uploadType=multipart&name=readme.txt' \
--header 'Content-Type: multipart/form-data' \
--form 'file=@"<FileLocation>"'`

The content of my file is: `Sample text`
and the response keep telling me that: 

> invalid character 'S' looking for beginning of value

So, what is the correct way to send multi-part request into your gcs-server? I tried uploadType=media and it works perfectly fine

**Comment by fsouza** [comment]
Google Cloud Storage doesn't support `form-data`. The emulator matches the GCS API. This page should have more information: https://cloud.google.com/storage/docs/uploading-objects#rest-upload-objects

**Comment by nhatmvo** [comment]
Hi @fsouza, thank you so much for a quick reply.
Anyway, I changed the Content-Type into another value, and my request is:

`curl --location --request POST 'https://localhost:4443/upload/storage/v1/b/sample-bucket/o?uploadType=multipart&name=readme.txt' \
--header 'Content-Type: text/plain;boundary=test' \
--data-binary '<FileLocation>'`

but I get this error:

> multipart: NextPart: EOF

I'm wondering what's wrong with my request this time :(
Thank you!

**Comment by fsouza** [comment]
The body must contain metadata in json format separated by the boundary: https://cloud.google.com/storage/docs/uploading-objects#single-request-upload-that-includes-object-metadata (this link will let you fill-in the data)

So in your case your file would need to have content that looks something like this (untested):

```
--test
Content-Type: application/json; charset=UTF-8

{"name":"readme.txt","metadata":{"key1":"value1"}}

--test
Content-Type: text/plain; charset=UTF-8

Sample text
--test--
```

**Comment by nhatmvo** [comment]
Thank you so much!
