### ISSUE TITLE
Add a dockerized server configuration

### ISSUE THREAD

**Issue by jwhitlock** [fsouza/fake-gcs-server#45]
https://github.com/teone/gc-fake-storage provides a ``Dockerfile`` and related scripts to allow this code to be run as a server, so that it can be used outside of tests of Go code. This Docker image is published at https://hub.docker.com/r/matteoscandolo/gc-fake-storage.

It would be easier to improve and test this use case if the Docker configuration was part of this project instead. It could be easier to coordinate creating a new image when the library changes. Also, contributors could collaborate on language-specific clients, verified by integration tests.

There is no explicit license on https://github.com/teone/gc-fake-storage, which I believe means @teone has the copyright, which makes it incompatible with this project's BSD 2 license, copyright Francisco Souza. I believe the clearest way to merge the code is if @teone makes the initial PR, which makes it clear he's contributing under the license for this this project. After the initial merge of files, I'd be happy to make additional changes. 
 
This was first discussed on closed PR https://github.com/fsouza/fake-gcs-server/pull/39#issuecomment-501852822

**Comment by fsouza** [comment]
@jwhitlock I'm planning to give a shot at this next week. If we don't hear back from @teone, I can create a different main package under ``cmd/fake-gcs`` (or ``cmd/gcs-emulator``, dunno).

**Comment by teone** [comment]
Hi @fsouza and @jwhitlock <https://github.com/jwhitlock>,
I'll be more than happy to make a pull request!

I should be able to do it aome time next week

**Comment by fsouza** [comment]
Nice! Will wait then :D

**Comment by fsouza** [comment]
@jwhitlock @teone please take a look at #46.
