### ISSUE TITLE
Incorrect content type?

### ISSUE THREAD

**Issue by cgreening** [fsouza/fake-gcs-server#451]
Thanks for the great library. I'm struggling to get it working with Rails - does anyone have this working?

I think one of the issues I'm seeing is caused by an incorrect content type stopping the ruby library from parsing the responses.

```
curl -i http://0.0.0.0:4443/storage/v1/b/test
HTTP/1.1 200 OK
Date: Mon, 15 Mar 2021 09:59:42 GMT
Content-Length: 111
Content-Type: text/plain; charset=utf-8

{"kind":"storage#bucket","id":"test","name":"test","versioning":{},"timeCreated":"2021-03-15T09:59:06.41438Z"}
```

**Comment by cgreening** [comment]
I've hacked around with the code and added the correct content type and it fixes my issue with ruby not parsing the response. I'm not a go developer, but I'll try and pull together a pull request with a fix.

**Comment by fsouza** [comment]
Oh interesting, I thought we had the proper content-types, but probably only on download. Should be an easy fix though. Let me know if you have any questions or would prefer me to fix it.
