### ISSUE TITLE
[Feature Request] add support for startOffset and endOffset

### ISSUE THREAD

**Issue by jschaf** [fsouza/fake-gcs-server#464]
The GCP storage API allows specifying an inclusive startOffset and exclusive endOffset to fetch a range of objects. The fake storage server ignores both parameters, returning all objects instead.

https://cloud.google.com/storage/docs/json_api/v1/objects/list

**Comment by boisamazing** [comment]
I've been working on pagination using fake-gcs-server and need also supports for **maxResults** and **pageToken**.

**Comment by lucaspin** [comment]
Hey @fsouza, I bumped into this issue this week and opened #528 to address it. I'd really appreciate a review from you on that one when you get a chance.
