### ISSUE TITLE
Trying to download blob calls original googleapis url

### ISSUE THREAD

**Issue by kye308** [fsouza/fake-gcs-server#53]
Hi, thanks for all the great work so far! I'm interested in downloading files with the server and am not sure if that is supported right now.

I can follow the steps in the readme to get a blob object. I would like to call `blob.download_as_string()` (or any similar download function) but when I do, I get 

```
Unauthorized: 401 GET https://www.googleapis.com/download/storage/v1/b/<bucket>/o<object_name>?alt=media: (u'Request failed with status code', 401, u'Expected one of', 200, 206)
```
Is this expected? Wasn't sure if blob download is supported atm.

**Comment by fsouza** [comment]
Hi @kye308 can you try the example from the [examples](https://github.com/fsouza/fake-gcs-server/tree/master/examples/python) folder?

**Comment by fsouza** [comment]
I just replaced the snippet with a direct link. The script is also being tested in our CI environment now, so we should be good!

Please feel free to reopen if you still encounter this issue.
