### ISSUE TITLE
Add support for negative offset

### ISSUE THREAD

**Issue by Leavrth** [fsouza/fake-gcs-server#536]
It seems that negative offset is not considered, such as `range=-10-` which means `NewRangeReader(ctx, -10, -1)`.
https://github.com/fsouza/fake-gcs-server/blob/5a7dc5a5a672ab1b61ed7a9d4180614d60245975/fakestorage/object.go#L578-L599

It can be seen in `Example(LastNBytes)` in https://pkg.go.dev/cloud.google.com/go/storage#ObjectHandle.NewRangeReader

**Comment by dnerdy** [comment]
I'd like to fix this. Note that I don't believe `Range: bytes=-10-` is a valid range. A range with an offset from the end of the content looks like `Range: bytes=-10`. I also noticed it's possible to cause fake-gcs-server to panic by requesting an out-of-bound range. GCS returns a 416 when the range start is past the end of the content, and ignores other invalid ranges (i.e. it returns a 200 response will the entire content).
