### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by wgreeneactual** [fsouza/fake-gcs-server#588]
We have a few Python apps that have used this tool reliably until we recently updated our CentOS base image to deal with some expired certificates. Now we are having errors when we try to make requests to `fake-gcs-server` within a docker network. This was working without any issue until we made that change.  Have you seen anything like this?

`HTTPSConnectionPool(host='fake-gcs-server', port=4443): Max retries exceeded with url: /upload/storage/v1/b/os-create-order/o?uploadType=multipart (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))`

Forgive the limited details.

Thanks,
Will

**Comment by fsouza** [comment]
@wgreeneactual hmm that as a new error is unexpected, fake-gcs-server has always run with a self-signed certificate. More specifically, it uses a self-signed certificate that ships with Go's httptest.Server.

Did you have any logic to trust the CA? Did anything change on the client side making the call to fake-gcs-server?

**Comment by wgreeneactual** [comment]
Thank you for the response. This may well be an issue with our client. As far as I know we are just using this import from the Google SDK and not messing with any of the internals of that:

`from google.cloud.storage import Bucket`

The only change was to update the CentOS Docker image to fix an expired certificate in an outdated image. I don't know too much about the details on that, it's lower down the stack from what I am familiar with. It is quite possible there are some other moving parts. I just wanted to see if anyone else had reported anything like this. 

I was able to work around the issue by switching to `-scheme http`.

Thanks again, I appreciate the follow up and if I determine the actual root cause I'll update.
