### ISSUE TITLE
Allow specification of Location

### ISSUE THREAD

**Issue by mdedetrich** [fsouza/fake-gcs-server#590]
I am attempting to use face-gcs-server along with [Alpakka](https://github.com/akka/alpakka), specifically https://github.com/akka/alpakka/tree/master/google-cloud-storage/src and I am currently experiencing the issue where when you try to get the details of a bucket (i.e. `GET http://0.0.0.0//storage/v1/b/<some-bucket>`) the response is missing the `location` field in the JSON.

I understand that fake-gcs-server doesn't return a `location` field because fake-gcs-server doesn't really have a concept  of `location` but since its a mandatory field this is causing alpakka gcs client to not work, the JSON deserialization is failing with

```
Message: Object is missing required member 'location'
```

Maybe it makes sense to add a `-location` parameter the options which can hardcode a location (such as `"EUROPE-WEST3"`)? Alternately when you create a bucket that specifies a `location` this can be persisted so that its returned whenever you do  `GET http://0.0.0.0//storage/v1/b/<some-bucket>`.

**Comment by fsouza** [comment]
Yeah if that's a parameter on bucket creation we should persist it and return where applicable.

Do you know if any other fields are missing?

**Comment by mdedetrich** [comment]
> Do you know if any other fields are missing?

Unfortunately the JSON parser that is used short circuits as soon as it finds the first missing field so I only know that the `location` field is missing but for reference these are the fields that its looking for (all of which are mandatory)

```scala
final class Bucket private (
    val name: String,
    val location: String,
    val kind: String,
    val id: String,
    val selfLink: String,
    val etag: String
)
```

If this is not helpful enough I can print out the response to see if there are any other missing fields?

**Comment by fsouza** [comment]
Oh ok from that type definition I assume the only thing missing is location. I can work on it some time this week, but let me know if you'd prefer to send a PR.

I think we probably want to:

- take the region on createBucket
- include it on getBucket
- (maybe?) have a default region that's used for buckets sourced from the disk on startup

**Comment by mdedetrich** [comment]
>  I can work on it some time this week, but let me know if you'd prefer to send a PR.

I am not that familiar with Go and its not that urgent for me so I am happy waiting if you are fine with working on it (otherwise let me know and I will try and work on it later on).

> I think we probably want to:

> take the region on createBucket
> include it on getBucket
> (maybe?) have a default region that's used for buckets sourced from the disk on startup

Yup sounds great from my end, having a command line arg such as `default-region` seems appropriate for the last point
