### ISSUE TITLE
Store objects as binary instead of JSON

### ISSUE THREAD

**Issue by gaul** [fsouza/fake-gcs-server#671]
Storing objects in binary more efficient than encoding as JSON which has high memory usage for large files.  fake-gcs-server can store the metadata in extended attributes instead.  References #669.

**Comment by fsouza** [comment]
Yeah using JSON isn't great, specially when we're dealing with ranges. It also means we can't store metadata for buckets (as they're represented as simple folders). I wonder if using extended attributes will limit what kind of filesystem we can use (I haven't done this before, so I really don't know), but we can definitely explore it.

Alternatively we can always have a metadata file in some structured format, in addition with the actual content.
