### ISSUE TITLE
The dependency on cloud.google.com/go doesn't need to be 0.19.0

### ISSUE THREAD

**Issue by gracenoah** [fsouza/fake-gcs-server#7]
In Gopkg.toml, there's a dependency on
```
  name = "cloud.google.com/go"
  version = "0.19.0"
```
and this was forcing me to upgrade cloud.google.com/go, but fake-gcs-server doesn't actually depend on anything new in this version, so I would prefer it if a lower version was required, such as 0.18.0. I'm working around this with a fork because I already have a fork, but maybe there's a way to tell dep to override it. Either way, it seems simple enough to lower the required version in this repo. Any objections?

**Comment by fsouza** [comment]
Hey @gracenoah, can you try overriding it in your ``Gopkg.toml``?

```
[[override]]
  name = "cloud.google.com/go"
  version = "0.18.0"
```

**Comment by gracenoah** [comment]
Ah, sorry, yes, the override does work as expected. I'm pretty impressed with dep :P Feel free to close if you think that's a reasonable compromise.

**Comment by fsouza** [comment]
@gracenoah thanks for confirming! :D
