### ISSUE TITLE
Missing `generation` field causes issues with official Google PHP Client

### ISSUE THREAD

**Issue by veteran29** [fsouza/fake-gcs-server#701]
When a file is uploaded to the bucket with the PHP client provided by Google it expects `generation` field in the response, see:
https://github.com/googleapis/google-cloud-php-storage/blob/main/src/Bucket.php#L301

Could you please change it so this field is present with a `null` value instead of omitting it from serialization when it's not set?

**Comment by fsouza** [comment]
Oh interesting. Yeah that should be an easy change. Do you want to send a PR or do you want me to do it? I should be able to do it later today.

**Comment by veteran29** [comment]
I would be grateful if you could please do this. I do not code in Go (It looks pretty simple to get into though!) and just wanted to use this project with Google PHP SDK.

**Comment by fsouza** [comment]
> I would be grateful if you could please do this. I do not code in Go (It looks pretty simple to get into though!) and just wanted to use this project with Google PHP SDK for Cloud Storage. 

Sorry I didn't get to it today but I will make the change tomorrow.

**Comment by fsouza** [comment]
Hmm I'm curious whether the GCS API returns `""`, `"0"` or `null`. Do you have an example from a real request? If not, I can get one later.

**Comment by veteran29** [comment]
I've done a quick test upload via their web interface and got `generation: "1646335421345034"` for empty txt file.
It looks like it's Epoch in microseconds as it matches upload time.

**Comment by fsouza** [comment]
@veteran29 sorry completely missed this, do you know what the API returns if generation is disabled in the bucket? I'll give it a try on the weekend.

**Comment by seniorcatDDL** [comment]
Hi, any updates here? I have the same problem with php client

**Comment by fsouza** [comment]
> Hi, any updates here? I have the same problem with php client

Sorry, still didn't get a chance to inspect what the value should be when the bucket has versioning disabled. Do you know what the API returns if generation is disabled in the bucket?

I know I can create a bucket and check, but wondering if this is something y'all can help with.

**Comment by mmetayer** [comment]
As far as I understand the docs (https://cloud.google.com/storage/docs/object-versioning and https://cloud.google.com/storage/docs/metadata#generation-number) there is always a generation number returned, whether the versioning is enabled or not.

**Comment by seniorcatDDL** [comment]
I can help with this issue, if you tell me where to edit the server response please

**Comment by fsouza** [comment]
@veteran29 @seniorcatDDL I believe this is a limitation in the filesystem backend only? It should be solved when we fully implement versioning in that backend, but a quicker fix is available in #812. Could you give that a try?

Thanks for your patience!

**Comment by fsouza** [comment]
Closed via 230d2a3d35d32efcaa5450004792582ee539226e.

**Comment by seniorcatDDL** [comment]
Thank you, I'll definitely try it today

**Comment by seniorcatDDL** [comment]
Works great, thanks a lot!
Is it possible to update a docker image?

**Comment by fsouza** [comment]
> Is it possible to update a docker image?

Should be up in a couple of minutes, I made a mistake when tagging it yesterday. Sorry about that.
