### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by frallain** [fsouza/fake-gcs-server#8]
Hi, I am really interested by this initiative to mimick GCS a la fakes3. Some questions though, 
- how to start the server? 
- what are the dependencies?
Cheers

**Comment by fsouza** [comment]
@frallain hey, it looks like you want to use this as a standalone server/daemon? fake-gcs-server is a library, you can create a custom application server out of it, but you'd need to write the code to do so.

Not sure if that answers your question. Please let me know if that's not the case! :)

**Comment by stern0** [comment]
I think it would be better to have make it as standalone daemon or server executable as a rest api service, in that case any programming language can consume it, like how this [fake-s3](https://github.com/jubos/fake-s3) is implemented . Now as it is only golang developers can use this.

**Comment by gracenoah** [comment]
This is how I use it:

```go
package main

import (
	"fmt"

	"github.com/fsouza/fake-gcs-server/fakestorage"
)

func main() {
	server, err := fakestorage.NewServerWithOptions(fakestorage.Options{
		InitialObjects: []fakestorage.Object{
			{
				BucketName: "bucket",
				Name:       "bucket-precreate-object",
				Content:    []byte("This object just forces the bucket to exist when the server starts up."),
			},
		},
		Host:        "0.0.0.0",
		Port:        4443,
		StorageRoot: "/storage",
	})
	if err != nil {
		panic(err)
	}
	fmt.Printf("Server started at %s\n", server.URL())
	select {}
}
```

I also use it the original intended way as a library with in-memory storage in tests, but this is really useful for integration tests.

**Comment by kaskerd** [comment]
So this can only be used in golang projects right? 

It's not like the ruby version which seems to run as a service.

**Comment by teone** [comment]
Hi @fsouza,
first thing, thanks for creating this!

I'm trying to use this as a fake backend to create standalone server (as @cllty suggested). 
Using @gracenoah suggestion I quickly containerized it and it's running exposing port `9000`.

When I run a `curl` against it I receive a `AccessDenied` as in:
```
curl 127.0.0.1:9000/storage/v1/b
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>v1/b</Key><BucketName>storage</BucketName><Resource>/storage/v1/b</Resource><RequestId>158FE5F2C8F655B8</RequestId><HostId>7f2ab8aa-98eb-494c-bb79-7d25ec4d7724</HostId></Error>
```

I couldn't find any reference to credentials in the code, so any guidance on the usage of the server will be much appreciated.

Thanks in advance

**Comment by teone** [comment]
ok, never mind and sorry for the stupid question... I didn't realize the connection was trough `https` and that's why it was running on port `4443`, exposing that port works:

```
curl --insecure https://127.0.0.1:4443/storage/v1/b
{
  "kind": "storage#buckets",
  "items": [
    {
      "kind": "storage#bucket",
      "ID": "bucket",
      "Name": "bucket"
    }
  ],
  "prefixes": null
}
```

**Comment by fsouza** [comment]
Hey @teone, I think I'll implement a fake--gcs command and containerize that to facilitate testing applications that are not using Go. And would include some docs too. Would that be helpful?

**Comment by teone** [comment]
@fsouza I was waiting to arrive to a more stable point with that but I started looking at that yesterday: https://github.com/teone/gc-fake-storage I'd be happy to contribute this back here if others are interested in it

**Comment by fsouza** [comment]
Oh cool, if you have it I can link it in the README too :)

**Comment by teone** [comment]
Sure I'll send you a PR for that as soon as it's in a decent shape!
