### ISSUE TITLE
Missing Docker v1.38.1 and Wrong Tag Format

### ISSUE THREAD

**Issue by burakince** [fsouza/fake-gcs-server#815]
Hi,

Docker push workflow looks like needs a [`v` tag at the beginning of tag name](https://github.com/fsouza/fake-gcs-server/blob/fbeb0c2d8aa1b941d9d5e0655ca71435ae382a0f/.github/workflows/docker-push.yml#L5). But unfortunately somehow latest [1.38.1 tag](https://github.com/fsouza/fake-gcs-server/releases/tag/1.38.1) didn't use `v` at the beginning of name and docker push pipeline didn't run. Could you please help to solve the problem?

Thanks,
Burak Ince

**Comment by fsouza** [comment]
> Docker push workflow looks like needs a v tag at the beginning of tag name. But unfortunately somehow latest 1.38.1 tag didn't use v at the beginning of name and docker push pipeline didn't run. Could you please help to solve the problem?

That was my mistake, I'll fix it.

**Comment by fsouza** [comment]
This is fixed now, thanks for reporting!
