### ISSUE TITLE
Multi-part upload isn't supported in all cases

### ISSUE THREAD

**Issue by nhoughto** [fsouza/fake-gcs-server#84]
Using the Java SDK in this fashion

`bucketStorage.create(BlobInfo.newBuilder(bucketInfo, fullKey).build(), inputstream);`

Appears to send data using an unsupported mechanism, gives this error:

```
multipart: NextPart: EOF

com.google.cloud.storage.StorageException: 500 Internal Server Error
multipart: NextPart: EOF

	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:310)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:180)
```

**Comment by nhoughto** [comment]
I see looking through the code that there is a section for multipart uploads, possibly multi part uploads from the java sdk behave slightly differently?

Is there a way to enable more logging to give you more information?

**Comment by nhoughto** [comment]
Ah this is because the java sdk sending protobuf/grpc by default, not JSON. Trying to figure out if can configure it to use JSON instead.. there is this sdk that is deprecated

https://developers.google.com/api-client-library/java/apis/storage/v1

**Comment by nhoughto** [comment]
Works with old java sdk with gzip disabled :+1:

**Comment by nhoughto** [comment]
@fsouza Any plan for adding a gRPC interface to this? This was the cause of my java sdk problems in the end.

**Comment by fsouza** [comment]
@nhoughto I believe this would be way more complex. I don't have any plans right now, but I also don't have enough information. I can investigate and write down my findings.

**Comment by nhoughto** [comment]
Ok that would be great, grpc appears to be the future for gcp apis, only the deprecated GCS library does JSON now. So someone is going to have to do it eventually 😉.

And you appear to be the only project out there solving this problem! 🤞🏼

**Comment by DanieleSassoli** [comment]
@fsouza any chance you looked into this? I'm hitting the same issue and not really in a position where I can use the deprecated SDK, it'd be great if this could work as, as @nhoughto says, you're the only one providing a docker emulator for gcs.
