### ISSUE TITLE
Support notificationConfigs API

### ISSUE THREAD

**Issue by pckhoi** [fsouza/fake-gcs-server#898]
Any plan to support `/storage/v1/b/BUCKET_NAME/notificationConfigs` operations as described [here](https://cloud.google.com/storage/docs/reporting-changes#enabling)? I could take a stab at this if no one is working on it.

**Comment by fsouza** [comment]
Hey @pckhoi, would we integrate it with the existing pubsub implementation?

As far as I know, no one is working on it, and a patch is welcome, but I'm curious on how it'd work.

**Comment by pckhoi** [comment]
My requirements have changed and I no longer need this feature. Feel free to close then.

**Comment by fsouza** [comment]
Thanks for confirming. I'll close it and then we can revisit if someone suggests it again.
