### ISSUE TITLE
Ability to change log level

### ISSUE THREAD

**Issue by Meemaw** [fsouza/fake-gcs-server#932]
By default, `fake-gcs-server` is quite spammy, doing info logging for every request.

Add an ability to change the log level to e.g `warn/error`

**Comment by fsouza** [comment]
That sounds good to me. We can add a new flag (and eventually an environment variable when we solve #561).

**Comment by RachitSharma2001** [comment]
@fsouza @Meemaw I was wondering if I could pick this task up. My idea is to include a `log-level` flag which can be one of three options:
1. all
2. only-warnings-and-errors
3. only-errors
Let me know what you think of this idea and if there is anything else I should change or add.

**Comment by fsouza** [comment]
Hey @RachitSharma2001, I was thinking the flag would be a string and take anything that logrus accept. You could call [`ParseLevel`](https://pkg.go.dev/github.com/sirupsen/logrus#ParseLevel) and if that fails, you report an error to the user indicating invalid log level or something like that.

**Comment by RachitSharma2001** [comment]
That sounds good! I have made a PR for this. Let me know if there is anything that should be changed or added.
