### ISSUE TITLE
invalid bucket name

### ISSUE THREAD

**Issue by enumag** [fsouza/fake-gcs-server#940]
I'm trying to create a bucket using the curl commands from readme:

```
curl -i -X POST http://0.0.0.0:4443/storage/v1/b \
   -H 'Content-Type: application/json' \
   -d '{"kind":"storage#buckets","items":[{"kind":"storage#bucket","id":"sample-bucket","name":"sample-bucket"}],"prefixes":null}'
```

However it fails like this:

```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Wed, 05 Oct 2022 11:12:35 GMT
Content-Length: 69

{"error":{"code":400,"message":"invalid bucket name","errors":null}}
```

**Comment by fsouza** [comment]
Hey @enumag, thanks for opening this issue. It seems that you're using the wrong payload? The docs have more info: https://cloud.google.com/storage/docs/json_api/v1/buckets/insert

The payload should be something like `{"name":"sample-bucket"}`.

**Comment by enumag** [comment]
I was using the payload from readme: https://github.com/fsouza/fake-gcs-server#preload-data

**Comment by fsouza** [comment]
The example in the README is a list request with no payload.

 `{"kind":"storage#buckets","items":[{"kind":"storage#bucket","id":"sample-bucket","name":"sample-bucket"}],"prefixes":null}` is the response, not payload.

Let me know if there are any changes that we can make to the README to make this clearer.
