### ISSUE TITLE
contentType not returned for yaml files

### ISSUE THREAD

**Issue by cobyforrester** [fsouza/fake-gcs-server#990]
Hello!

When running a get request on `.json` files, the `contentType` is set as `application/json`, but for `.yaml` it is missing entirely. 

`curl http://0.0.0.0:4443/storage/v1/b/sample_bucket/o/sample_folder%2Fsample.json`
yields:
```
{
"id":"sample_bucket/sample_folder/sample.json",
"bucket":"sample_bucket",
"size":"5133",
"contentType":"application/json",
 ...
}
```
`curl http://0.0.0.0:4443/storage/v1/b/sample_bucket/o/sample_folder%2Fsample.yaml`
yields (same but with no contentType):
```
{
"id":"sample_bucket/sample_folder/sample.yaml",
"bucket":"sample_bucket",
"size":"5133",
 ...
}
```

Whereas GCS returns `"contentType": "application/x-yaml"`.

I imagine this could happen with other file formats, but I primarily work with yaml files. Assumably the fix is just adding extra content type detection.

**Comment by fsouza** [comment]
Are you running it locally or using the Docker image? Basically, fake-gcs-server leverages the OS-level content-type mapping, and maybe the one in alpine doesn't have a mapping for yaml? Or perhaps the mailcap package no longer includes those (json is builtin to Go, so it always works).

Just trying to understand how we fix it :)

**Comment by fsouza** [comment]
Oh OK I see that alpine's /etc/mime.types doesn't have yaml: 

```
％ docker run -it --entrypoint /bin/sh fsouza/fake-gcs-server -c 'grep yml /etc/mime.types'
％ docker run -it --entrypoint /bin/sh fsouza/fake-gcs-server -c 'grep yaml /etc/mime.types'
```

**Comment by cobyforrester** [comment]
I am running it in Docker, so that absolutely makes sense!

**Comment by fsouza** [comment]
I spent some time on this and it seems like the easiest thing to do is to manually add the content-type for yaml 🤔 

Sent #991, will merge it once it's green.
